### ISSUE TITLE
Build fail on Linux Mint: "GL/glew.h: No such file or directory"

### ISSUE THREAD

**Issue by ghost** [fredakilla/uspark#1]
When trying to build uspark with QtCreator on Linux Mint 64-bit I get the following compiler error:
> /home/frode/Git/uspark/spark/src/Rendering/OpenGL/SPK_GL_PointRenderer.cpp:23: error: GL/glew.h: No such file or directory

I tried adding `LIBS = -lGL` to the `.pro`-file, to no avail. Am I missing something?

**Comment by fredakilla** [comment]
I think you need libglew-dev 
Try : sudo apt-get install libglew-dev


It's only required for the "01_sdl_test" sample, you also need ftgl freetype and sdl2.
If you don't want to install them, just remove sample 01 form uspark.pro, urho samples don't need that.

**Comment by ghost** [comment]
Indeed that fixed that, thanks!
